services:
  db:
    image: postgres:15-alpine
    container_name: smart-home-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  telemetry-service:
    build:
      context: ./backend
      dockerfile: telemetry_service/Dockerfile
    container_name: telemetry_service
    restart: always
    ports:
      - "8001:8000"  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "8000:8000"  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  ai-service:
    build:
      context: ./backend
      dockerfile: ai_service/Dockerfile
    container_name: ai_service
    restart: always
    ports:
      - "8002:8000"  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: